# Generated by Django 5.2.5 on 2025-09-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Szemely',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vezeteknev', models.CharField(max_length=100)),
                ('keresztnev', models.CharField(max_length=100)),
                ('eletkor', models.IntegerField()),
                ('hazas', models.BooleanField(default=False)),
                ('elettortenet', models.TextField()),
                ('letrehozva', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Családtagok',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('created', models.DateField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Teendők',
            },
        ),
    ]
